build: solution.cpp
	g++ --std=c++23 solution.cpp -o solution

run: solution
	./solution input.txt

test: solution
	./solution test-input.txt
	cat test-output.txt


build2: task2.cpp
	g++ --std=c++23 task2.cpp -o task2

run2: task2
	./task2 input.txt

test2: task2
	./task2 test-input.txt
	cat test-output-2.txt
